# Generated by Django 3.2.9 on 2021-12-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricecard',
            old_name='price_description',
            new_name='pc_description',
        ),
        migrations.RenameField(
            model_name='pricecard',
            old_name='price_value',
            new_name='pc_value',
        ),
        migrations.RenameField(
            model_name='pricetable',
            old_name='price_new',
            new_name='pt_new',
        ),
        migrations.RenameField(
            model_name='pricetable',
            old_name='price_old',
            new_name='pt_old',
        ),
        migrations.RenameField(
            model_name='pricetable',
            old_name='price_title',
            new_name='pt_title',
        ),
    ]
